import { AlertTriangle, ArrowRight, BarChart3, TrendingUp } from 'lucide-react';
import { Link } from 'react-router-dom';
import { PageHeader } from '../components/PageHeader';
import { Button } from '../components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '../components/ui/card';
import { Progress } from '../components/ui/progress';
import { formatBr } from '../lib/currency';
import { byCategory, overspendItems, projectTotals } from '../lib/insights';
import { useAppStore } from '../store/useAppStore';

export function InsightsPage() {
  const project = useAppStore((s) => s.project); const categories = useAppStore((s) => s.categories); const estimateItems = useAppStore((s) => s.estimateItems); const expenses = useAppStore((s) => s.expenses); const wishlist = useAppStore((s) => s.wishlistItems);
  const totals = projectTotals(estimateItems, expenses, project.totalBudget); const categoriesData = byCategory(categories, estimateItems, expenses); const overspends = overspendItems(estimateItems, expenses); const openWishlist = wishlist.filter((item) => item.status !== 'bought').reduce((sum, item) => sum + item.price * item.quantity, 0); const forecast = totals.fact + Math.max(0, totals.expected - totals.fact) + openWishlist; const forecastDelta = forecast - totals.limit;
  return <div className="space-y-5"><PageHeader title="Анализ бюджета" subtitle="План, факт и прогноз без сложных таблиц" action={<Button asChild size="sm" variant="outline"><Link to="/report">Отчёт <ArrowRight /></Link></Button>} />
    <div className="grid gap-3 sm:grid-cols-3"><Metric label="Потрачено" value={formatBr(totals.fact)} detail={`из ${formatBr(totals.limit)}`} /><Metric label="Прогноз итоговой суммы" value={formatBr(forecast)} detail={forecastDelta > 0 ? `выше бюджета на ${formatBr(forecastDelta)}` : `запас ${formatBr(-forecastDelta)}`} danger={forecastDelta > 0} /><Metric label="Неоплачено по смете" value={formatBr(Math.max(0, totals.expected - totals.fact))} detail="без будущих покупок" /></div>
    <Card className={forecastDelta > 0 ? 'border-red-500/30 bg-red-500/5' : 'border-emerald-500/25 bg-emerald-500/5'}><CardContent className="flex gap-3 p-5"><span className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-2xl ${forecastDelta > 0 ? 'bg-red-500/15 text-red-600' : 'bg-emerald-500/15 text-emerald-600'}`}>{forecastDelta > 0 ? <AlertTriangle /> : <TrendingUp />}</span><div><p className="font-semibold">{forecastDelta > 0 ? 'Бюджет под риском' : 'Бюджет выглядит устойчиво'}</p><p className="mt-1 text-sm text-muted-foreground">Прогноз включает уже оплаченные расходы, остаток по смете и незакрытые покупки из списка «К покупке».</p></div></CardContent></Card>
    <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><BarChart3 className="h-4 w-4 text-primary" />Расходы по категориям</CardTitle></CardHeader><CardContent className="space-y-4">{categoriesData.length === 0 ? <p className="text-sm text-muted-foreground">Пока нет данных.</p> : categoriesData.map(({ category, plan, fact }) => { const percent = plan ? fact / plan * 100 : fact ? 100 : 0; return <div key={category.id}><div className="mb-1.5 flex justify-between gap-3 text-sm"><span className="flex items-center gap-2 font-medium"><i className="h-2.5 w-2.5 rounded-full" style={{ background: category.color }} />{category.name}</span><span className={fact > plan && plan > 0 ? 'font-semibold text-red-600' : 'text-muted-foreground'}>{formatBr(fact)} / {formatBr(plan)}</span></div><Progress value={Math.min(percent, 100)} indicatorClassName={percent > 100 ? '!bg-red-500' : undefined} /></div>; })}</CardContent></Card>
    <Card><CardHeader><CardTitle className="text-base">Точки перерасхода</CardTitle></CardHeader><CardContent>{overspends.length === 0 ? <p className="text-sm text-muted-foreground">Перерасходов по привязанным позициям пока нет.</p> : <div className="space-y-2">{overspends.slice(0, 5).map(({ item, plan, fact, diff }) => <div key={item.id} className="flex items-center justify-between gap-3 rounded-2xl bg-red-500/5 px-3 py-2.5"><span className="min-w-0 truncate text-sm font-medium">{item.name}</span><span className="shrink-0 text-right text-xs"><b className="text-red-600">+{formatBr(diff)}</b><br /><span className="text-muted-foreground">{formatBr(fact)} из {formatBr(plan)}</span></span></div>)}</div>}</CardContent></Card>
  </div>;
}
function Metric({ label, value, detail, danger }: { label: string; value: string; detail: string; danger?: boolean }) { return <Card><CardContent className="p-4"><p className="text-xs font-medium text-muted-foreground">{label}</p><p className={`mt-1 text-xl font-bold tracking-tight ${danger ? 'text-red-600' : ''}`}>{value}</p><p className="mt-1 text-xs text-muted-foreground">{detail}</p></CardContent></Card>; }
