import { FileDown, Share2 } from 'lucide-react';
import { toast } from 'sonner';
import { PageHeader } from '../components/PageHeader';
import { Button } from '../components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '../components/ui/card';
import { formatBr } from '../lib/currency';
import { byStage, byZone, projectTotals } from '../lib/insights';
import { useAppStore } from '../store/useAppStore';

export function ReportPage() {
  const project = useAppStore((s) => s.project); const zones = useAppStore((s) => s.zones); const stages = useAppStore((s) => s.stages); const estimateItems = useAppStore((s) => s.estimateItems); const expenses = useAppStore((s) => s.expenses); const totals = projectTotals(estimateItems, expenses, project.totalBudget); const zoneRows = byZone(zones, estimateItems, expenses); const stageRows = byStage(stages, estimateItems); const date = new Date().toLocaleDateString('ru-BY');
  const share = async () => { const text = `${project.name || 'МойРемонт'}\nПотрачено: ${formatBr(totals.fact)}\nБюджет: ${formatBr(totals.limit)}\nОстаток: ${formatBr(totals.remain)}`; try { if (navigator.share) await navigator.share({ title: 'Отчёт по ремонту', text }); else { await navigator.clipboard.writeText(text); toast.success('Краткий отчёт скопирован'); } } catch { /* пользователь отменил отправку */ } };
  return <div className="space-y-5 print:space-y-3"><PageHeader title="Отчёт по ремонту" subtitle={`Сформирован ${date}`} action={<div className="flex gap-2 print:hidden"><Button size="sm" variant="outline" onClick={share}><Share2 />Поделиться</Button><Button size="sm" onClick={() => window.print()}><FileDown />PDF / печать</Button></div>} />
    <Card className="border-primary/25 bg-gradient-to-br from-primary/10 via-card to-card"><CardContent className="grid gap-4 p-5 sm:grid-cols-3"><div><p className="text-xs text-muted-foreground">Проект</p><p className="mt-1 text-lg font-bold">{project.name || 'МойРемонт'}</p></div><div><p className="text-xs text-muted-foreground">Потрачено</p><p className="mt-1 text-lg font-bold">{formatBr(totals.fact)}</p></div><div><p className="text-xs text-muted-foreground">Остаток бюджета</p><p className={`mt-1 text-lg font-bold ${totals.remain < 0 ? 'text-red-600' : 'text-emerald-600'}`}>{formatBr(totals.remain)}</p></div></CardContent></Card>
    <div className="grid gap-4 md:grid-cols-2"><Card><CardHeader><CardTitle className="text-base">По зонам</CardTitle></CardHeader><CardContent className="space-y-3">{zoneRows.map(({ zone, plan, fact }) => <div key={zone.id} className="flex justify-between gap-3 text-sm"><span className="flex items-center gap-2"><i className="h-2.5 w-2.5 rounded-full" style={{ background: zone.color }} />{zone.name}</span><span className="text-right text-muted-foreground">{formatBr(fact)} / {formatBr(plan)}</span></div>)}</CardContent></Card><Card><CardHeader><CardTitle className="text-base">Этапы работ</CardTitle></CardHeader><CardContent className="space-y-3">{stageRows.map(({ stage, progress, plan }) => <div key={stage.id} className="flex justify-between gap-3 text-sm"><span>{stage.name}</span><span className="text-right text-muted-foreground">{Math.round(progress)}% · {formatBr(plan)}</span></div>)}</CardContent></Card></div>
    <Card><CardHeader><CardTitle className="text-base">Последние расходы</CardTitle></CardHeader><CardContent className="space-y-2">{[...expenses].sort((a,b) => b.date.localeCompare(a.date)).slice(0, 8).map((expense) => <div key={expense.id} className="flex justify-between gap-3 border-b border-border/60 py-2 text-sm last:border-0"><span className="min-w-0 truncate">{expense.comment || 'Расход'} <span className="text-muted-foreground">· {new Date(expense.date + 'T12:00:00').toLocaleDateString('ru-BY')}</span></span><b className="shrink-0">{formatBr(expense.amount)}</b></div>)}{expenses.length === 0 && <p className="text-sm text-muted-foreground">Расходов пока нет.</p>}</CardContent></Card>
  </div>;
}
